apiVersion: v1
kind: Secret
metadata:
  name: flask-credentials
type: Opaque
stringData:
  POSTGRES_USER: appuser
  POSTGRES_PASSWORD: week3-demo-only
  DATABASE_URL: postgresql://appuser:week3-demo-only@db:5432/statustracker
